CREATE TABLE LOGIN (
	IDLOGIN VARCHAR(12) NOT NULL,
	PASSWORD VARCHAR(12) NOT NULL,
	CONSTRAINT LOGIN_PK PRIMARY KEY (IDLOGIN)
)

CREATE TABLE ADMIN_SA (
	ID_ADMIN VARCHAR(12) NOT NULL,
	NAMA_ADMIN VARCHAR(30),
	IDLOGIN VARCHAR(12) NOT NULL,
	CONSTRAINT ADMIN_SA_PK PRIMARY KEY (ID_ADMIN),
	CONSTRAINT LOGIN_FK FOREIGN KEY (IDLOGIN)
	REFERENCES  LOGIN (IDLOGIN) ON DELETE CASCADE
)

CREATE TABLE TAGIHAN (
	NOMOR_TAGIHAN VARCHAR(12) NOT NULL ,
	JUMLAH_TAGIHAN INT,
	CONSTRAINT TAGIHAN_PK PRIMARY KEY (NOMOR_TAGIHAN)
)

CREATE TABLE LAPORAN_AKADEMIK (
	ID_LAPORAN VARCHAR(12) NOT NULL ,
	NAMA_LAPORAN VARCHAR(15),
	JUMLAH_LAPORAN INT,
	CONSTRAINT LAPORAN_AKADEMIK_PK PRIMARY KEY (ID_LAPORAN)
)

CREATE TABLE REGISTRASI (
	KODE_REGISTRASI VARCHAR(8) NOT NULL ,
	CONSTRAINT REGISTRASI_PK PRIMARY KEY (KODE_REGISTRASI)
)

CREATE TABLE MENGELOLA (
	ID_ADMIN VARCHAR(12) NOT NULL ,
	KODE_REGISTRASI VARCHAR(8) NOT NULL ,
	ID_LAPORAN VARCHAR(12) NOT NULL ,
	NOMOR_TAGIHAN VARCHAR(12) NOT NULL ,
	CONSTRAINT MENGELOLA_FK1 FOREIGN KEY (ID_ADMIN)
	REFERENCES  ADMIN_SA (ID_ADMIN) ON DELETE CASCADE ,
	CONSTRAINT MENGELOLA_FK2 FOREIGN KEY (KODE_REGISTRASI)
	REFERENCES  REGISTRASI (KODE_REGISTRASI) ON DELETE CASCADE ,
	CONSTRAINT MENGELOLA_FK3 FOREIGN KEY (ID_LAPORAN)
	REFERENCES  LAPORAN_AKADEMIK (ID_LAPORAN) ON DELETE CASCADE ,
	CONSTRAINT MENGELOLA_FK4 FOREIGN KEY (NOMOR_TAGIHAN)
	REFERENCES  TAGIHAN (NOMOR_TAGIHAN) ON DELETE CASCADE
)

CREATE TABLE  MAHASISWA (
	NIM VARCHAR(12) NOT NULL ,
	NAMAMHS VARCHAR(30),
	ALAMATMHS VARCHAR(40),
	IDLOGIN VARCHAR(12) NOT NULL ,
	CONSTRAINT MHS_PK PRIMARY KEY (NIM) ,
	CONSTRAINT MHS_FK FOREIGN KEY (IDLOGIN)
	REFERENCES  LOGIN (IDLOGIN) ON DELETE CASCADE
   )

CREATE TABLE MATAKULIAH (
	KODEMK VARCHAR(12) NOT NULL ,
	NAMAMK VARCHAR(30),
	SKS INT,
	KELAS VARCHAR(10),
	HARI VARCHAR(6),
	JAM TIME,
	CONSTRAINT MATAKULIAH_PK PRIMARY KEY (KODEMK,KELAS)
)

CREATE TABLE DOSEN (
	KODE_DOSEN VARCHAR(12) NOT NULL ,
	NAMA_DOSEN VARCHAR(30),
	KEAHLIAN VARCHAR(20),
	IDLOGIN VARCHAR(12) NOT NULL ,
	CONSTRAINT DOSEN_PK PRIMARY KEY (KODE_DOSEN) ,
	CONSTRAINT DOSEN_FK FOREIGN KEY (IDLOGIN)
	REFERENCES  LOGIN (IDLOGIN) ON DELETE CASCADE
)

CREATE TABLE MENGAMBIL_MK (
	NIM VARCHAR(12) NOT NULL ,
	KODEMK VARCHAR(12) NOT NULL ,
	KODE_DOSEN VARCHAR(12) NOT NULL ,
	UTS INT(3),
	UAS INT(3),
	TUGAS INT(3),
	CONSTRAINT MENGAMBIL_FK1 FOREIGN KEY (NIM)
	REFERENCES  MAHASISWA (NIM) ON DELETE CASCADE ,
	CONSTRAINT MENGAMBIL_FK2 FOREIGN KEY (KODEMK)
	REFERENCES  MATAKULIAH (KODEMK) ON DELETE CASCADE ,
	CONSTRAINT MENGAMBIL_FK3 FOREIGN KEY (KODE_DOSEN)
	REFERENCES  DOSEN (KODE_DOSEN) ON DELETE CASCADE,
	CONSTRAINT MENGAMBIL_PK PRIMARY KEY (NIM,KODEMK)
)

CREATE TABLE KOMUNIKASI (
	NIM VARCHAR(12) NOT NULL ,
	KODE_DOSEN VARCHAR(12) NOT NULL ,
	PESAN TEXT,
	CONSTRAINT KOMUNIKASI_FK1 FOREIGN KEY (NIM)
	REFERENCES  MAHASISWA (NIM) ON DELETE CASCADE ,
	CONSTRAINT KOMUNIKASI_FK2 FOREIGN KEY (KODE_DOSEN)
	REFERENCES  DOSEN (KODE_DOSEN) ON DELETE CASCADE
)
